rule Mimikatz_Logfile {
  meta:
    author = Spider
    comment = None
    date = 2015/03/31
    description = Detects a log file generated by malicious hack tool mimikatz
    family = None
    hacker = None
    judge = unknown
    license = https://creativecommons.org/licenses/by-nc/4.0/
    reference = None
    score = 80
    threatname = Mimikatz[Logfile
    threattype = Logfile.yar
  strings:
    $s1 = "SID               :" ascii fullword
    $s2 = "* NTLM     :" ascii fullword
    $s3 = "Authentication Id :" ascii fullword
    $s4 = "wdigest :" ascii fullword
  condition:
    all of them
}