rule Payload_Exe2Hex {
  meta:
    author = Spider
    comment = None
    date = 2016-01-15
    description = Detects payload generated by exe2hex
    family = None
    hacker = None
    judge = unknown
    license = https://creativecommons.org/licenses/by-nc/4.0/
    reference = https://github.com/g0tmi1k/exe2hex
    score = 70
    threatname = Payload[Exe2Hex
    threattype = Exe2Hex.yar
  strings:
    $a1 = "set /p \"=4d5a" ascii
    $a2 = "powershell -Command \"$hex=" ascii
    $b1 = "set+%2Fp+%22%3D4d5" ascii
    $b2 = "powershell+-Command+%22%24hex" ascii
    $c1 = "echo 4d 5a " ascii
    $c2 = "echo r cx >>" ascii
    $d1 = "echo+4d+5a+" ascii
    $d2 = "echo+r+cx+%3E%3E" ascii
  condition:
    all of ($a*) or all of ($b*) or all of ($c*) or all of ($d*)
}