rule apt_nix_elf_derusbi {
  meta:
    author = "Spider"
    comment = "None"
    date = "2016/02/29"
    description = "Detects Derusbi Backdoor ELF"
    family = "None"
    hacker = "None"
    judge = "black"
    reference = "https://github.com/fideliscyber/indicators/tree/master/FTA-1021"
    threatname = "None"
    threattype = "None"
  strings:
    $s1 = "LxMain"
    $s2 = "execve"
    $s3 = "kill"
    $s4 = "cp -a %s %s"
    $s5 = "%s &"
    $s6 = "dbus-daemon"
    $s7 = "--noprofile"
    $s8 = "--norc"
    $s9 = "TERM=vt100"
    $s10 = "/proc/%u/cmdline"
    $s11 = "loadso"
    $s12 = "/proc/self/exe"
    $s13 = "Proxy-Connection: Keep-Alive"
    $s14 = "Connection: Keep-Alive"
    $s15 = "CONNECT %s"
    $s16 = "HOST: %s:%d"
    $s17 = "User-Agent: Mozilla/4.0"
    $s18 = "Proxy-Authorization: Basic %s"
    $s19 = "Server: Apache"
    $s20 = "Proxy-Authenticate"
    $s21 = "gettimeofday"
    $s22 = "pthread_create"
    $s23 = "pthread_join"
    $s24 = "pthread_mutex_init"
    $s25 = "pthread_mutex_destroy"
    $s26 = "pthread_mutex_lock"
    $s27 = "getsockopt"
    $s28 = "socket"
    $s29 = "setsockopt"
    $s30 = "select"
    $s31 = "bind"
    $s32 = "shutdown"
    $s33 = "listen"
    $s34 = "opendir"
    $s35 = "readdir"
    $s36 = "closedir"
    $s37 = "rename"
  condition:
    uint32(0) == 0x4464c457f and all of them
}