rule EquationGroup_scanner_output {
  meta:
    author = "Spider"
    comment = "None"
    date = "2017-04-17"
    description = "Detects output generated by EQGRP scanner.exe"
    family = "None"
    hacker = "None"
    judge = "black"
    license = "https://creativecommons.org/licenses/by-nc/4.0/"
    reference = "Internal Research"
    threatname = "None"
    threattype = "None"
  strings:
    $s0 = "# scanning ip  " ascii
    $s1 = "# Scan for windows boxes" ascii fullword
    $s2 = "Going into send" ascii fullword
    $s3 = "# Does not work" ascii fullword
    $s4 = "You are the weakest link, goodbye" ascii fullword
    $s5 = "rpc   Scan for RPC  folks" ascii fullword
  condition:
    filesize < 1000KB and 2 of them
}