rule EQGRP_sniffer_xml2pcap {
  meta:
    author = "Spider"
    comment = "None"
    date = "2016-08-16"
    description = "EQGRP Toolset Firewall - file sniffer_xml2pcap"
    family = "None"
    hacker = "None"
    hash1 = "f5e5d75cfcd86e5c94b0e6f21bbac886c7e540698b1556d88a83cc58165b8e42"
    judge = "unknown"
    license = "https://creativecommons.org/licenses/by-nc/4.0/"
    reference = "Research"
    threatname = "None"
    threattype = "None"
  strings:
    $x1 = "-s/--srcip <sourceIP>  Use given source IP (if sniffer doesn't collect source IP)" fullword ascii
    $x2 = "convert an XML file generated by the BLATSTING sniffer module into a pcap capture file." fullword ascii
  condition:
    1 of them
}